project-flogo/flogo-web

- libs/plugins/flow-server/src/lib/import/task-converter.ts
Make changes for v0.9.0 app subflow input mappins to work
fixes #1073
```
[x] Bugfix
[ ] Feature
```
Subflow input mappings are lost for v.0.9.0 app
Subflow input mappings will work as expected.
> fix(plugins-flow-server): Subflow input mappings are lost for V0.9.0 app

- apps/client/src/flogo/app/app-detail/app-detail.component.html
- apps/client/src/flogo/app/app-detail/app-detail.component.ts
- libs/plugins/flow-client/src/lib/flow.component.html
Made changes to fix application description issue, deleted empty file, corrected a typo
fixes #1067
```
[x] Bugfix
[ ] Feature
```
Application description is missing in the webui
Fixed the issue to show application description
> fix(plugins-flow-client): Application description is missing

- apps/client/src/flogo/app/app-detail/app-detail.component.html
- apps/client/src/flogo/app/app-detail/app-detail.component.spec.ts
- apps/client/src/flogo/app/app-detail/app-detail.component.ts
- apps/client/src/flogo/app/core/app-resources-state.service.ts
- apps/client/src/flogo/app/core/apps.service.spec.ts
- apps/client/src/flogo/app/core/apps.service.ts
- apps/client/src/flogo/app/core/get-shim-build-options.ts
- apps/client/src/flogo/app/core/index.ts
fixes #1068
```
[X] Bugfix
[ ] Feature
```
When I create a flow or delete a flow in the application details page and try to export the application I do not see the latest set of resources
The flows list for the Export flow is loaded once when we launch application details page and never updated. The list is now taking the recent set of resources.
> [1068] Showing latest list of applications

- apps/client/src/flogo/app/app-detail/app-detail.component.ts
Fixes template can't access private method.
> fix(client): unaccessible service in template

- apps/server/src/modules/transfer/export/app-formatter/app-formatter.ts
- apps/server/src/modules/transfer/export/app-formatter/handler-format.ts
```
[X] Bugfix
[ ] Feature
```
Fixes #1044 where there are few appModel fields which are added as empty objects when they are not configured or when their configurations are removed.
> [1044] Remove empty object for appModel properties while exporting

- apps/server/src/common/contrib-schema-normalize.js
removed earlier added normalization logic which is now fixed in descriptor
fixes #1013
```
[] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Removed schema normalization logic earlier added as it is now fixed in descriptor json
> fix(server): remove schema normalization logic

- apps/server/src/config/sample-app.json
- apps/server/src/modules/transfer/common/normalize-handler-mappings.ts
- apps/server/src/modules/transfer/export/app-formatter/handler-format.spec.ts
- apps/server/src/modules/transfer/export/app-formatter/handler-format.ts
- libs/core/src/lib/engine/interfaces.ts
```
[x] Bugfix
[ ] Feature
```
Cannot export or build the sample app, it displays an unknown error in the UI. Upon inspection I found out the server export code couldn't handle empty handler mappings.
Added case for empty handler mappings to export. Exporting/building the sample app works now.
> Fix empty handler mappings

- README.md
- apps/server/src/modules/apps/schemas/app-schema.json
- apps/server/src/modules/apps/schemas/full-app-schema.json
- apps/server/src/modules/base-registered/package.tpl.json
- docs/engine-interaction.md
- libs/lib-server/core/src/lib/schemas/v1.0.0/app.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/common.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/flow.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/schema-namespace.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/trigger.json
- libs/plugins/flow-server/src/lib/import/action-importer.ts
- package.json
Update references from `github.com/TIBCOSoftware/flogo-web` to `github.com/project-flogo/flogo-web`.
> Update repo URL references to `project-flogo/flogo-web`

- apps/client/src/flogo/home/apps-list/apps-list.component.ts
- apps/client/src/flogo/home/import-errors/import-errors.component.ts
```
[X] Bugfix
[ ] Feature
```
With #1100 changes, we missed the functionality which resets the import file input. Without which we cannot import the same file again.
Resetting the import file input field so user can select the same file again.
> Resetting import file input

- libs/lib-client/header/src/index.ts
- libs/lib-client/header/src/lib/header.component.html
- libs/lib-client/header/src/lib/header.component.less
- libs/lib-client/header/src/lib/header.component.spec.ts
- libs/lib-client/header/src/lib/header.component.ts
- libs/lib-client/header/src/lib/header.module.spec.ts
- libs/lib-client/header/src/lib/header.module.ts
- libs/lib-client/header/tslint.json
- tsconfig.json
- Added header component as a library so that we can use it again for
streams
- Added inputs to send the actual data of the resource to header
component
- Updated the styles of the back icon and application name
- Enabled Delete functionality
- Added content editor to resource name and description
- Changes to name and description informs the consumer by events
Fixes #1112
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
The …
> Extracted the header component as a client library

- apps/client/src/flogo/core/core.module.ts
- apps/client/src/flogo/core/navbar/navbar.component.less
- apps/client/src/flogo/core/navbar/navbar.component.ts
- apps/client/src/flogo/core/navbar/navbar.tpl.html
- libs/lib-client/contrib-installer/src/index.ts
- libs/lib-client/contrib-installer/src/lib/contrib-installer.component.html
- libs/lib-client/contrib-installer/src/lib/contrib-installer.component.less
- libs/lib-client/contrib-installer/src/lib/contrib-installer.component.ts
- libs/lib-client/contrib-installer/src/lib/contrib-installer.module.ts
- libs/lib-client/contrib-installer/src/lib/url-installer/url-installer.component.html
- libs/lib-client/contrib-installer/src/lib/url-installer/url-installer.component.ts
- libs/lib-client/modal/src/modal-control.ts
- libs/lib-client/modal/src/modal.service.ts
- libs/plugins/flow-client/src/lib/task-add/task-add.component.html
- libs/plugins/flow-client/src/lib/task-add/task-add.component.spec.ts
- libs/plugins/flow-client/src/lib/task-add/task-add.component.ts
- libs/plugins/flow-client/src/lib/triggers/triggers.component.html
- libs/plugins/flow-client/src/lib/triggers/triggers.component.spec.ts
- libs/plugins/flow-client/src/lib/triggers/triggers.component.ts
update styles of global install button, move global install from bootstrap modal to cdk overlay
Fixes #1110
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
```
Moved contrib installation from bootstrap modal to CDK overlay. Implemented styles for global install button
> refactor(client): update styles of global install button, move global install from bootstrap modal to cdk overlay

- .env.example
- apps/client/src/flogo/flogo.module.ts
- apps/server/src/api/v2/index.ts
- apps/server/src/config/app-config.js
- apps/server/src/config/index.ts
- apps/server/src/config/is-feature-enabled.ts
- apps/server/src/config/parse-features-toggles.ts
- libs/lib-client/core/src/services/feature-toggles.ts
- libs/lib-client/core/src/services/index.ts
Introduce feature toggles in client and server to enable integration of new features directly in the main branch.
> feat: introduce feature toggles

- .travis.yml
- make-web.sh
- tools/docker/Dockerfile
- tools/docker/ml.Dockerfile
```
[ ] Bugfix
[x] Feature
```
**What is the current behavior?** 
See https://github.com/project-flogo/flogo-web/issues/1105
1. Switched the base image from alpine to a debian based image to correct issues related to compilation of C libraries
2. Build and auto push a docker image targeted for ML development
> Use debian as base for docker image and build ML image

- apps/server/src/configure-engines.ts
- apps/server/src/server.ts
Fix db changes are not persisted in dev env
> fix(server): fix db won't persist in dev env

- apps/server/package.json
- tools/release/post-build-apps.js
```
[ ] Bugfix
[ ] Feature
[ x ] Refactoring (no functional changes, no api changes)
```
Server package json start script is added dynamically from the typescript code
To make it less confusing and easy to understand moved the start script command to package.json
**Other information**:
> Moving server start to package.json

- apps/server/src/modules/transfer/export/action-agent/create-action-agent.ts
- apps/server/src/modules/transfer/export/app-formatter/app-formatter.ts
- apps/server/src/modules/transfer/export/app-formatter/handler-format.ts
- apps/server/src/modules/transfer/export/export-app.spec.ts
- libs/core/src/lib/engine/interfaces.ts
- libs/lib-server/core/src/lib/extensions/resource-exporter.ts
- libs/plugins/stream-core/src/index.ts
- libs/plugins/stream-core/src/lib/engine.ts
- libs/plugins/stream-core/src/lib/interfaces/index.ts
- libs/plugins/stream-core/src/lib/stream.ts
- libs/plugins/stream-server/src/lib/export/format-stages.ts
- libs/plugins/stream-server/src/lib/export/index.ts
- libs/plugins/stream-server/src/lib/export/register-action.ts
- libs/plugins/stream-server/src/lib/export/resource.ts
- libs/plugins/stream-server/src/lib/stream-server.ts
```
[ ] Bugfix
[X] Feature
```
fixes #1149 
While exporting the application, stream resources are also exported as expected. An action for each stream resource is created and the same is linked to the handler.
> [1149] Exporting application supports stream resources 

- apps/server/src/modules/transfer/import/import-app.ts
- apps/server/src/modules/transfer/import/imports/extract-actions-agent.ts
- apps/server/src/modules/transfer/import/imports/extract-actions.ts
- apps/server/src/modules/transfer/import/imports/index.ts
- libs/lib-server/core/src/lib/extensions/resource-importer.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/action.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/app.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/common.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/flow.json
- libs/lib-server/core/src/lib/schemas/v1.0.0/index.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/tests/app.spec.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/tests/common.spec.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/tests/flow.spec.ts
- libs/lib-server/core/src/lib/schemas/v1.0.0/trigger.json
- libs/plugins/flow-server/src/lib/export/tests/export.spec.ts
- libs/plugins/flow-server/src/lib/import/action-importer.spec.ts
- libs/plugins/stream-core/src/lib/engine.ts
- libs/plugins/stream-server/src/lib/constants.ts
- libs/plugins/stream-server/src/lib/export/format-stages.ts
- libs/plugins/stream-server/src/lib/export/register-action.ts
- libs/plugins/stream-server/src/lib/import/handler.ts
- libs/plugins/stream-server/src/lib/import/index.ts
- libs/plugins/stream-server/src/lib/import/make-resource-validator.ts
- libs/plugins/stream-server/src/lib/import/schemas/action-settings.json
- libs/plugins/stream-server/src/lib/import/schemas/index.ts
- libs/plugins/stream-server/src/lib/import/schemas/resource.json
- libs/plugins/stream-server/src/lib/import/schemas/stream-data.json
- libs/plugins/stream-server/src/lib/import/stream.ts
- libs/plugins/stream-server/src/lib/stream-server.ts
```
[ ] Bugfix
[X] Feature
```
Fixes #1150 
This changes will support the streams as a resource in application JSON.
- Added validations for stream plugin and `actions` property in application JSON
- Added an Actions Manager which will register and fetch the actions
- Import the stream's handler and resource
> [1150] Supports streams while importing an application

- libs/lib-client/core/src/services/log.service.ts
```
[x] Bugfix
[ ] Feature
```
Engine log is empty and there's an error in the console:
Logs are displayed again.
> fix(client): logs are not displayed

- libs/plugins/stream-client/src/lib/core/effects/stream-save.effects.ts
- libs/plugins/stream-client/src/lib/core/state/index.ts
- libs/plugins/stream-client/src/lib/stage-add/add-activity.service.ts
- libs/plugins/stream-client/src/lib/stage-add/models/stage-add-action-creator.ts
- libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.ts
- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Fixes #1166
> (stream-client):Rename StreamDiagramActions as StreamActions

- libs/plugins/stream-server/src/lib/constants.ts
- libs/plugins/stream-server/src/lib/hooks.ts
- libs/plugins/stream-server/src/lib/import/handler.ts
- libs/plugins/stream-server/src/lib/import/index.ts
- libs/plugins/stream-server/src/lib/import/make-resource-validator.ts
- libs/plugins/stream-server/src/lib/import/schemas/index.ts
- libs/plugins/stream-server/src/lib/is-stream-resource.ts
- libs/plugins/stream-server/src/lib/schemas/action-settings.json
- libs/plugins/stream-server/src/lib/schemas/common.json
- libs/plugins/stream-server/src/lib/schemas/index.ts
- libs/plugins/stream-server/src/lib/schemas/internal-schema.json
- libs/plugins/stream-server/src/lib/schemas/resource.json
- libs/plugins/stream-server/src/lib/schemas/stream-data.json
- libs/plugins/stream-server/src/lib/stream-server.ts
```
[ ] Bugfix
[X] Feature
```
The create and update stream resource are not validated for the data. 
The stream changes won't be saved if there is any invalid data
> Added validation for update and create stream actions in server

- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.less
- libs/plugins/stream-client/src/lib/triggers/triggers.component.html
- libs/plugins/stream-client/src/lib/triggers/triggers.component.less
```
[x] Bugfix
[x] Feature
```
Fixes #1197
> stream diagram issues. Fixes #1197

- apps/server/src/modules/contrib-install-controller/index.ts
```
[x] Bugfix
[ ] Feature
```
Can't install a contribution as reported in #1193
Contributions can be installed again
> fix(server): unable to install contributions

- libs/assets/styles/_mapper-modal.less
- libs/plugins/flow-client/src/lib/shared/mapper/list/list.component.less
- libs/plugins/flow-client/src/lib/shared/mapper/tree/tree.component.less
- libs/plugins/stream-client/src/lib/shared/mapper/list/list.component.less
```
[x] Bugfix
[ ] Feature
```
flow-branch, flow-trigger, flow-task and stream-stage components have scroll issues (overflow content is hidden).
flow-branch, flow-trigger, flow-task and stream-stage components do not have scroll issues (overflow content can be scrolled).
**Other information**:
Fixes #1199
> fix: scroll issues in mapper screens

- .travis.yml
This reverts commit 65b203ac as issue has already been fixed
> revert: "build: disabling ML build while inference issue is fixed"

- libs/plugins/flow-client/src/lib/flow.component.html
- libs/plugins/flow-client/src/lib/flow.component.ts
- libs/plugins/flow-client/src/lib/flow.module.ts
- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.html
- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.less
- libs/plugins/flow-client/src/lib/params-schema/params-schema.component.html
- libs/plugins/flow-client/src/lib/params-schema/params-schema.component.less
- libs/plugins/flow-client/src/lib/params-schema/params-schema.component.ts
- libs/plugins/flow-client/src/lib/params-schema/params-schema.module.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Replace bs-modal by cdk-modal in params-schema component. This eliminates the dependency on jquery for params-schema-component.
```
**Other information**:
Replaced bs-modal by cdk-modal in params-schema component. Modified the Params-Schema modal as per new design. Add functionality to select/unselect groupBy property.
Fixes a part(Params-Schema-Input/output) of #900
> Enhancements to the param schema modal in Flows.

- apps/demo-libs/src/app/app.component.ts
- apps/demo-libs/src/app/app.module.ts
- apps/demo-libs/src/app/search/index.ts
- apps/demo-libs/src/app/search/people.component.html
- apps/demo-libs/src/app/search/people.component.less
- apps/demo-libs/src/app/search/people.component.ts
- apps/demo-libs/src/app/search/person.ts
- apps/demo-libs/src/app/search/search.component.html
- apps/demo-libs/src/app/search/search.component.less
- apps/demo-libs/src/app/search/search.component.ts
- apps/demo-libs/src/styles.less
- libs/lib-client/search/README.md
- libs/lib-client/search/src/index.ts
- libs/lib-client/search/src/local-search.provider.ts
- libs/lib-client/search/src/local-search.ts
- libs/lib-client/search/src/search.module.ts
- libs/lib-client/search/src/search/search.component.html
- libs/lib-client/search/src/search/search.component.less
- libs/lib-client/search/src/search/search.component.ts
- tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Search component and search logic is repeated in multiple places.
Added a new module in lib-client (`@flogo-web/lib-client/search`) that:
1. Provides a reusable search component that implements most of the standard search features.
2. Provides a utility class `LocalSearch` that encapsulates reusable search logic. It also implements a factory to …
> feat: add search client library

- apps/demo-libs/src/app/search/search.component.html
- apps/demo-libs/src/app/search/search.component.less
- apps/demo-libs/src/app/search/search.component.ts
- libs/assets/styles/uxpl/search.less
- libs/lib-client/search/README.md
- libs/lib-client/search/src/index.ts
- libs/lib-client/search/src/local-search.provider.ts
- libs/lib-client/search/src/local-search.ts
- libs/lib-client/search/src/search/search.component.html
- libs/lib-client/search/src/search/search.component.less
- libs/lib-client/search/src/search/search.component.ts
Adding additional features to search component.
Changes required to support current use cases:
- allow to position search icon
- remove function provider factory as it is not compatible with angular's AOT
- support adding initial value to search component
- query should remember last emission and not not emit empty on re-subscribe
Manual testing, updated search demo in demo-libs app
> feat(lib-client): enhancements to search component

- apps/server/src/common/utils/ensure-unique-resource.ts
- apps/server/src/modules/resources/resource-service.ts
- apps/server/src/modules/transfer/import/import-app.ts
fixes #1195
```
[x] Bugfix
[ ] Feature
```
**What is the current behavior?** 
When an application is imported without resource name, they are treated as undefined in ui. Fixes #1195 
Generate a unique resource name if any of the imported resources doesn't have a name.
> fix: ensure resource has name with uniqueness

- apps/client/src/flogo/app/new-resource/new-resource.component.ts
- apps/server/src/plugins.ts
Removed streams feature flag.
Stream functionality is ready to be made available by default
> chore: make streams available by default

- libs/assets/styles/_mixins.less
- libs/lib-client/search/README.md
- libs/plugins/flow-client/src/lib/core/flow.service.ts
- libs/plugins/flow-client/src/lib/flow.module.ts
- libs/plugins/flow-client/src/lib/shared/flows-list/flow/flows-list-flow.component.html
- libs/plugins/flow-client/src/lib/shared/flows-list/flow/flows-list-flow.component.less
- libs/plugins/flow-client/src/lib/shared/flows-list/flow/flows-list-flow.component.ts
- libs/plugins/flow-client/src/lib/shared/flows-list/flows-list.component.html
- libs/plugins/flow-client/src/lib/shared/flows-list/flows-list.component.less
- libs/plugins/flow-client/src/lib/shared/flows-list/flows-list.component.spec.ts
- libs/plugins/flow-client/src/lib/shared/flows-list/flows-list.component.ts
- libs/plugins/flow-client/src/lib/shared/flows-list/flows-list.module.ts
- libs/plugins/flow-client/src/lib/sub-flow/index.ts
- libs/plugins/flow-client/src/lib/sub-flow/sub-flow.component.html
- libs/plugins/flow-client/src/lib/sub-flow/sub-flow.component.less
- libs/plugins/flow-client/src/lib/sub-flow/sub-flow.component.ts
- libs/plugins/flow-client/src/lib/sub-flow/sub-flow.module.ts
- libs/plugins/flow-client/src/lib/task-add/task-add.component.html
- libs/plugins/flow-client/src/lib/task-add/task-add.component.spec.ts
- libs/plugins/flow-client/src/lib/task-add/task-add.component.ts
- libs/plugins/flow-client/src/lib/task-add/task-add.module.ts
- libs/plugins/flow-client/src/lib/task-configurator/subflow-config.ts
- libs/plugins/flow-client/src/lib/task-configurator/subflow/subflow.component.html
- libs/plugins/flow-client/src/lib/task-configurator/subflow/subflow.component.less
- libs/plugins/flow-client/src/lib/task-configurator/subflow/subflow.component.ts
- libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.html
- libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.ts
- libs/plugins/flow-client/src/lib/task-configurator/task-configurator.module.ts
Refactored subflow selection components and implemented new design.
There was a new design implementation pending as well as we wanted to replace the BSModal external library with our internal implementation.
As part of the refactoring the search functionality of the subflow list has been removed from it and now it is external to the component, this allows more flexibility and reusability of the component as well as it was needed for the new design.
Manual testing
> refactor: subflow selector

- apps/server/src/api/v2/file-upload.ts
Delete previous uploaded files of a resource if any on successful upload of new file.
Fixes #1224
> fix: delete previous uploaded csv files

- libs/plugins/flow-client/src/lib/triggers/trigger-block/trigger-block.component.html
- libs/plugins/flow-client/src/lib/triggers/trigger-block/trigger-block.component.less
- libs/plugins/flow-client/src/lib/triggers/trigger-block/trigger-block.component.ts
- libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.html
- libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.less
- libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.ts
Remove unwanted lambda icon and its styles from trigger-block component of flow-client & stream-client. Fixes https://github.com/project-flogo/flogo-web/pull/1185#pullrequestreview-289790452
manually
> Remove special treatment for lambda icons from trigger-block component.

- apps/client/src/flogo/app/shared/menu-dropdown.less
- apps/client/src/flogo/core/navbar/navbar.component.less
- libs/lib-client/context-panel/src/context-panel.animations.ts
- libs/lib-client/logs/src/lib/logs.component.less
- libs/plugins/flow-client/src/lib/branch-configurator/branch-configurator.component.less
- libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.less
- libs/plugins/stream-client/src/lib/run-stream/run-stream.component.less
- libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.less
- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html
- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.less
- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
- libs/plugins/stream-client/src/lib/triggers/configurator/configurator.component.less
Fixes stacking issues of modals in flows and streams.
https://github.com/project-flogo/flogo-web/issues/1210
Manually
> Fix stacking issues of modals in flows and streams. Fixes #1210

- apps/server/src/api/v2/file-upload.ts
- apps/server/src/api/v2/resources/get-simulation-data-path.ts
- apps/server/src/api/v2/resources/remove-simulation-data.ts
- libs/plugins/stream-client/src/lib/run-stream/run-stream.component.ts
Unable to retrieve file details if resource id has '-' in between
> fix: unable to retrieve file details

- libs/plugins/stream-client/src/lib/core/effects/stream-save.effects.ts
Auto stop simulation if stream properties changes when simulation is in progress.
> auto stop simulation 

- libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
UI shows that only one stage can be added to the stream.
Fixes #1236
> fix add stage placeholders are missing in UI

- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.html
- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.less
- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.ts
- libs/plugins/stream-client/src/lib/params-schema/param-row-input/param-row-input.component.html
- libs/plugins/stream-client/src/lib/params-schema/param-row-input/param-row-input.component.less
- libs/plugins/stream-client/src/lib/params-schema/param-row-input/param-row-input.component.ts
- libs/plugins/stream-client/src/lib/params-schema/param-row-output/param-row-output.component.html
- libs/plugins/stream-client/src/lib/params-schema/param-row-output/param-row-output.component.less
- libs/plugins/stream-client/src/lib/params-schema/param-row-output/param-row-output.component.ts
Adds the functionality that toggles dropdown-menu in Params-Schema component of flows & streams.
Fixes #1246 
Manually
> merge: dropdown menu fix

- apps/client/src/flogo/app/resource-views/group-by-trigger/group-by-trigger.component.less
- apps/client/src/flogo/app/resource-views/resources/resource.component.less
- libs/assets/styles/uxpl/form.less
- libs/lib-client/trigger-selector/src/trigger-selector.component.less
- libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.less
- libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.less
- libs/plugins/stream-client/src/lib/triggers/trigger-block/trigger-block.component.less
Fixes 1, 3, 4, 5 issues of #1251 
Manually
> Fixes the styles issues specified in #1251

- libs/plugins/flow-client/src/lib/shared/mapper/services/mapper-controller/mapper-controller-factory.service.ts
Fixing the issue where clicking an activity name in flows will produce an invalid expression.
Fixes #1263
Manual changes
> fix(flow): unnecessary dot in root level mappings

- libs/plugins/flow-client/src/lib/shared/mapper/utils/mapper-translator.spec.ts
- libs/plugins/flow-client/src/lib/shared/mapper/utils/mapper-translator.ts
- libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.spec.ts
- libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.ts
> fix: convert single and back quote string to double quote

- apps/server/src/config/test-engine.config.json
- apps/server/src/init/bootstrap-engine.ts
Changes to flogo-web engine setup after Flogo core, flow, services  and stream releases.
> Removed master tags for flogo dependencies

- apps/server/src/modules/apps/apps-service.ts
- apps/server/src/modules/apps/build.ts
- apps/server/src/modules/engine/build/plugin.js
- libs/core/src/lib/constants/contributions-ref-placeholder.ts
##Description
fix(server): Updated the Lambda reference and also adapted to changes where to find the handler.zip output of the build
Fixes #1293 
Regression test. Tested cli trigger shim along with lambda trigger. Also tested building an application with more than one lambda trigger and shimming only one of them
> [1293] - Updated the lambda trigger reference

- apps/client/src/assets/main.less
- libs/lib-client/diagram/src/lib/drag-tiles/drag-tile.service.ts
Update cursor style of drag item as **dragging**
> fix: update drag tile cursor style dragging

- apps/server/src/common/utils/value-type.js
- apps/server/src/modules/transfer/tests/samples/imported-app.ts
Importing a resource with input/output of type **object** is changed to **any** in UI
Manually
> Fix import object type

- libs/lib-client/diagram/src/lib/diagram/diagram-row.component.html
- libs/plugins/flow-client/src/lib/core/models/flow/insert-node.ts
> fix(plugins-flow-client): add branch issue, show add between before return tile

- apps/server/src/modules/engine/icon-resolver.ts
- package.json
We are supporting only SVG type of images as contribution icons, extending support to PNG and JPG image types.
Part of #1261 
Mock trigger and activity with custom icons are available at fcastill/flogo-contrib-test. Added test PNG and JPG icons to the contributions, listed below
Support for SVG type icon can be tested by installing below contributions
- [github.com/fcastill/flogo-contrib-test/activity/log](https://github.com/fcastill/flogo-contrib-test/tree/master/activity/log)
- [github.com/fcastill/flogo-contrib-test/trigger/timer](https://github.com/fcastill/flogo-contrib-test/tree/master/trigger/timer)
Support for PNG type icon can be tested by installing below contributions
- [github.com/fcastill/flogo-contrib-test/activity/error](https://github.com/fcastill/flogo-contrib-test/tree/ma …
> feat(server): support png and jpg type contrib icons

- libs/plugins/stream-client/src/lib/simulator/_variables.less
- libs/plugins/stream-client/src/lib/simulator/simulator.component.html
- libs/plugins/stream-client/src/lib/simulator/simulator.component.less
- libs/plugins/stream-client/src/lib/simulator/simulator.component.ts
- libs/plugins/stream-client/src/lib/simulator/simulator.module.ts
- libs/plugins/stream-client/src/lib/stage-add/activity-list/activity.component.html
- libs/plugins/stream-client/src/lib/stage-add/activity-list/activity.component.less
- libs/plugins/stream-client/src/lib/stage-add/activity-list/activity.component.ts
- libs/plugins/stream-client/src/lib/stage-add/stage-add.module.ts
Added activity icon component in streams by emulating what was done with flow. 
Manually
> Added activity-icon component for streams

- .travis.yml
Travis is not complaining if the code format / code lint jobs fails. It's failing only if the last executed script in a stage errors.
Fixed it by updating CI config, adding a flag to fail the process if any of the scripts errors
> ci: update config to error if any of the scripts errors

- libs/lib-client/diagram/src/lib/tiles/tile-preview.component.html
- libs/plugins/flow-client/src/lib/debug-panel/debug-panel.component.html
> fix: drag preview tile styles

- apps/client/src/flogo/app/app-detail/app-detail.component.ts
- apps/client/src/flogo/app/app.module.ts
- libs/lib-client/activity-icon/src/activity-icon.component.html
- libs/lib-client/trigger-icon/src/trigger-icon.component.html
- libs/plugins/flow-client/src/lib/task-add/activity-list/activity.component.html
- libs/plugins/flow-client/src/lib/triggers/configurator/configurator.module.ts
- libs/plugins/flow-client/src/lib/triggers/configurator/confirmation/confirmation.component.html
- libs/plugins/flow-client/src/lib/triggers/triggers.component.ts
- libs/plugins/stream-client/src/lib/simulator/simulator.component.html
- libs/plugins/stream-client/src/lib/stage-add/activity-list/activity.component.html
- libs/plugins/stream-client/src/lib/triggers/configurator/configurator.module.ts
- libs/plugins/stream-client/src/lib/triggers/configurator/confirmation/confirmation.component.html
- libs/plugins/stream-client/src/lib/triggers/triggers.component.ts
- yarn.lock
This PR implements a "focus trap" in the confirmation modals of the trigger configuration so they're navigatable using keyboard.
Make it easier to navigate the app with keyboard.
Manually
> Trigger focus trap

- libs/plugins/flow-client/src/lib/params-schema/param-row/param-row.component.less
- libs/plugins/stream-client/src/lib/params-schema/param-row-input/param-row-input.component.less
- libs/plugins/stream-client/src/lib/params-schema/param-row-output/param-row-output.component.less
Misalignment of select input in the resource interface modal.
fixes #1336 
Manually
> select input misalignment in the resource interface modal

- apps/client/src/flogo/app/app-detail/app-detail.component.less
- apps/client/src/flogo/home/apps-list/apps-list.component.less
- apps/client/src/flogo/home/home.component.html
- apps/client/src/flogo/home/home.component.less
UI broken if the app/action name is too long.
Fixes #860
> fix: broken ui when app/action name is long
