project-flogo/flogo-web

apps/client/src/flogo/home/core/import-error-formatter.service.ts, apps/client/src/i18n/en.json
Made changes to show a descriptive message when an app is imported with unknown handler.
fixes #1070
```
[x] Bugfix
[ ] Feature
```
**What is the current behavior?** 
#1070 - Error message is not descriptive when an unknown handler is imported
Added a descriptive error message when an app with unknown handler is imported
=> fix(client): Import: error message is not described well for an unknown handler

.build_tags, .travis.yml, make-web.sh
- Allow to have a tag for Web UI different than the CLI and core versions
- Version CLI and core dependencies
- Push to dockerhub on build success. Pushing with tag `unstable`. Pushing it as private image for now.
=> ci: independent UI image tag and push to docker on master build success

apps/server/src/config/app-config.js, apps/server/src/modules/engine/registry.ts
The path to the default-contrib-bundle is messed recently and no longer found while starting the server. 
This change now requires the environment variable `FLOGO_WEB_DEFAULT_PALETTE` to provide full path of the file instead a file (similar to `FLOGO_WEB_DEFAULT_DESCRIPTOR`)
=> Fix wrong path to default-contrib-bundle file

apps/client/src/i18n/en.json, libs/lib-client/core/src/interfaces/graph/graph.ts, libs/lib-client/core/src/interfaces/graph/index.ts, libs/plugins/stream-client/src/lib/core/effects/stream-save.effects.ts, libs/plugins/stream-client/src/lib/core/models/generate-resource-from-state.ts, libs/plugins/stream-client/src/lib/core/models/graph-and-items/graph-creator.ts, libs/plugins/stream-client/src/lib/core/models/graph-and-items/stage-creator.ts, libs/plugins/stream-client/src/lib/core/models/handler-type.ts, libs/plugins/stream-client/src/lib/core/models/selection.ts, libs/plugins/stream-client/src/lib/core/models/stream/selection.ts, libs/plugins/stream-client/src/lib/core/state/cases/remove-stage.ts, libs/plugins/stream-client/src/lib/core/state/index.ts, libs/plugins/stream-client/src/lib/core/state/stream.actions.ts, libs/plugins/stream-client/src/lib/core/state/stream.reducers.ts, libs/plugins/stream-client/src/lib/core/state/stream.selectors.ts, libs/plugins/stream-client/src/lib/core/stream.service.ts, libs/plugins/stream-client/src/lib/stream-client.module.ts, libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.html, libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.less, libs/plugins/stream-client/src/lib/stream-diagram/index.ts, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.less, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.spec.ts, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
```
[ ] Bugfix
[X] Feature
```
Integrated the `flogo-diagram` library to the streams plugin code to allow users to design the streams. Current functionality achieved: 
1. Show existing stages in the diagram
2. Select a stage in the diagram
3. Delete a stage from the diagram. Can be tested in the branch [`1123-streams-diagram-test`](https://github.com/project-flogo/flogo-web/tree/1123-streams-diagram-test) where few of the stages are hard coded while initializing the stream state
WIP: …
=> [part of 1123] Implemented diagram module for streams to design the stream stages

.travis.yml
Missing libgconf in travis build is preventing e2e suite to run.
It seems it's either cause by Chrome that stopped depending on libgconf or Travis using newer Ubuntu versions that don't install libgconf by default.
=> fix(ci): added libgconf to travis build to run e2e suite

apps/server/src/config/default-flogo.json
```
[x] Bugfix
[ ] Feature
```
The engine displays an error that it failed to created due to invalid resource id. This can be observe in the log file in `/dist/local/logs/engine.log`
```
{"message":"2019-09-09T17:20:02.379-0700\tDEBUG\t[flogo] -\tRegistering type alias 'coerce' for function [github.com/project-flogo/contrib/function/coerce]","level":"info","timestamp":"2019-09-10T00:20:02.399Z"} …
```
=> fix(server): engine not starting due to wrong default resource

libs/plugins/stream-client/src/lib/shared/mapper/services/mapper-controller/mapper-controller-factory.service.ts, libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.ts, libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.ts, libs/plugins/stream-client/src/lib/triggers/configurator/trigger-detail/settings/form-field/form-field.component.html
show trigger outputs and stream outputs in available data while configuring a trigger.
Enable monaco-editor to input trigger and handler settings, includes review comments of pr#1163
Fixes #1168
```
[x] Bugfix
[ ] Feature
```
Unable to see the trigger outputs under Trigger Outputs while configuring the trigger-handler input mapping and stream outputs under Stream Outputs while configuring the trigger-handler …
=> fix: show trigger outputs and stream outputs in available data while configuring a trigger

libs/plugins/stream-client/src/lib/core/constants.ts, libs/plugins/stream-client/src/lib/core/state/clean-dangling-tasks-output-mappings.ts, libs/plugins/stream-client/src/lib/core/state/stream.reducers.ts, libs/plugins/stream-client/src/lib/shared/mapper/constants.ts, libs/plugins/stream-client/src/lib/shared/mapper/index.ts, libs/plugins/stream-client/src/lib/shared/mapper/services/mapper-controller/mapper-controller-factory.service.ts, libs/plugins/stream-client/src/lib/shared/mapper/utils/mapper-translator.ts, libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.ts
fixes #1161
```
[x] Bugfix
[ ] Feature
```
Deleting an output is not removing the dangling output mappings in a stage's configuration. Adding an output with the same name is pre-populated with previous mappings.
Deleting an output should remove the dangling output mappings
=> fix(stream-client): remove dangling output mappings when an output is deleted

angular.json, extra-webpack.config.js
```
[x] Bugfix
[ ] Feature
```
Warnings due to perspective plugin configuration.
Added custom plugin to remove unnecessary source map rule added by perspective webpack plugin.
=> fix(build): remove "SourceMap" warnings added by perspective webpack plugin

package.json, tools/schematics/lib-client/files/README.md, tools/schematics/lib-client/files/src/index.ts, tools/schematics/lib-client/index.ts, tools/schematics/lib-client/schema.json
Adds a schematic to automate the creation, setup and registration of shared client libraries under `lib-client` package.
To use run:
```bash
yarn flogo:new-client-lib <lib-name>
```
Where name is the desired name for the library, for example for 'context-panel'
```bash
yarn flogo:new-client-lib context-panel
```
This command will:
1. Add a new module in `libs/lib-client` that follows the same structure as the other modules in lib-client
2. Register a new entry in the root tsconfig.json as `@flogo-web/lib-client/<lib-name>` so the generated library can be used in other packages
The intention is to eliminate the multiple steps necessary to create a new client lib and consolidate it into one single step.
Manual testing
=> feat: add lib-client schematic

apps/server/src/modules/apps/handlers-service.ts, apps/server/src/modules/apps/triggers.ts, apps/server/src/modules/resources/resource-service.ts, libs/lib-client/core/src/services/app-resource.service.ts, libs/plugins/flow-client/src/lib/core/flow.service.ts, libs/plugins/flow-client/src/lib/flow.component.ts, libs/plugins/stream-client/src/lib/core/stream.service.ts
Fixes a bug where handlers have references to deleted resources, causing an exception while exporting / building a binary of the application
As per #1153, when we delete a resource, only first found trigger handler is deleted and other handlers used to maintain the reference to the deleted resource. 
Also if the trigger is not used by any other resources, then it was still maintained under existing triggers. Causing a lot of unused triggers in the application. There was no way to delete the un-referenced error
What problem does it solve?
When a resource is deleted, all the handlers associated with that resource are deleted. Also each delete resource operation is going to purge the unused triggers in the application
Manual testing
=> [1153] Deleting a resource will clean the triggers and handlers

libs/lib-server/core/src/lib/schemas/v1.0.0/tests/app.spec.ts, libs/lib-server/core/src/lib/schemas/v1.0.0/trigger.json
When there are no handlers provided for a trigger, the application import is failing with an exception. 
This ticket Fixes #1196.
Describe your changes in detail
I have updated the trigger schema and made handlers as required property. I followed the trigger configuration schema definition of flogo-core.
Manual testing
=> [1196] - Made handlers as a required property of the triggers

libs/plugins/stream-client/src/lib/run-stream/run-stream-button/run-stream-button.component.html
On run stream, run button is not changing to stop/pause/resume buttons
This is needed to pause/resume/stop stream
1) Create an app and an action stream
2) Add a stage, click run stream, upload a csv file
3) Click run stream
4) Now will be able to see stop/pause/resume
=> fix: subscribe to simulation process status

libs/plugins/flow-client/src/lib/core/state/flow/flow.selectors.ts
Fixes the functionality that sorts the activities list in activity-list component. It make sures that 'subflow' activity is always on the top and sorts the other activities alphabetically.
Manually
=> Sorts the contributions in add-activity modal with sub-flow contrib always at the top.

libs/plugins/stream-client/src/lib/run-stream/run-stream.component.ts, libs/plugins/stream-client/src/lib/run-stream/run-stream.service.ts
Upload popover is not closing after clicking run stream unless clicked outside the popover
Fixes #1239
=> merge: close upload popover on clicking run stream

apps/server/src/config/app-config.js, apps/server/src/config/default-flogo.json, apps/server/src/config/engine.json, apps/server/src/init/bootstrap-engine.ts, apps/server/src/modules/engine/engine.ts
feat(server): Added support to engine configuration file for local engine.
- Added a new app config property `defaultFlogoEngineConfigPath`
- Users can set environment variable FLOGO_WEB_DEFAULT_ENGINE_CONFIG to set the path to default engine config
- Users can provide a different path while updating the engine config
The latest flogo core provides support to maintain different engine configuration files which will be allow us to build the flogo-web's local engine binary with different test configurations.
Manual testing. 
1. Should not effect the new engine creation while the server start up
2. The telemetry service must be installed to the local engine through this engine config file
3. Should maintain a `engine.json` file in local engine's folder before building the local engine
=> Support the engine configuration file to the local engine

apps/server/src/config/app-config.js, apps/server/src/config/default-flogo.json, apps/server/src/config/engine.json, apps/server/src/init/bootstrap-engine.ts, apps/server/src/modules/engine/engine.ts
The engine config files are not available in the server application after build. Reverting #1250
=> Revert "Support the engine configuration file to the local engine"

apps/server/src/config/app-config.js, apps/server/src/config/default-flogo.json, apps/server/src/config/test-engine.config.json, apps/server/src/configure-engines.ts, apps/server/src/init/bootstrap-engine.ts, apps/server/src/modules/engine/engine.ts, apps/server/src/modules/engine/registry.ts
feat(server): Added support to engine configuration file for local engine.
- Added a new app config property `defaultFlogoEngineConfigPath`
- Users can set environment variable FLOGO_WEB_DEFAULT_ENGINE_CONFIG to set the path to default engine config
- Users can provide a different path while updating the engine config
The latest flogo core provides support to maintain different engine configuration files which will be allow us to build the flogo-web's local engine binary with different test configurations.
Manual testing. 
1. Should not effect the new engine creation while the server start up
2. The telemetry service must be installed to the local engine through this engine config file
3. Should maintain a `engine.json` file in local engine's folder before building the local engine
=> Separated test engine configuration from the actual application JSON

libs/plugins/flow-client/src/lib/debug-panel/debug-panel.component.ts, libs/plugins/flow-client/src/lib/debug-panel/utils.spec.ts, libs/plugins/flow-client/src/lib/debug-panel/utils.ts, libs/plugins/flow-client/src/lib/flow.component.ts, libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.html, libs/plugins/flow-client/src/lib/shared/dynamic-form/object/object-type.component.ts
Fixes #1272 
This change also fixes a console error we see in the browser when the client code is trying to see if the activity has run or not.
1. Have a flow with 2 rest activities (with one of them having some input data in debug panel preferably the later one)
2. Test run a flow from the beginning
3. Toggle between those 2 rest activities
4. You should be able to see that the inputs are updated with their respective data
5. Now select the 2nd rest activity and click on 'Run from this tile' in the debug panel. 
6. Toggle between the 2nd and 1st rest activity. The first activity being not ran in this cycle should have empty fields
=> fix: debug panel inputs were not updated

apps/server/src/modules/apps/app-importer.ts, libs/lib-server/core/src/lib/extensions/plugin.ts, libs/plugins/stream-core/src/lib/engine.ts, libs/plugins/stream-server/src/lib/constants.ts, libs/plugins/stream-server/src/lib/import/handler.ts, libs/plugins/stream-server/src/lib/import/stream.ts, libs/plugins/stream-server/src/lib/schemas/action-settings.json, libs/plugins/stream-server/src/lib/stream-server.ts
Adding `additionalResourceTypes` to the server plugin information to allow registering a plugin for more than one type of resource.
This is mainly to provide backwards support for streams due to the changes explained in #1269.
This PR also updates the stream server plugin to support both `streamURI`/`stream:` and `pipelineURI`/`pipeline:`.
Fixes https://github.com/project-flogo/flogo-web/issues/1269
=> fix(stream): support `streamURI` by default

apps/server/src/init/bootstrap-engine.ts, apps/server/src/modules/engine/registry.ts
use latest release of streams and don't sync imports during server startup
- depend on released version of streams instead of master
- speed up startup time #1274
=> use latest release of streams and don't sync imports during server startup

apps/server/src/modules/engine/process/exec-controller.ts
fix(server): Maintaining the flogo-web process properly in the engine-process-director in windows
Fixes #1277
Earlier we used to depend on `cmd.exe` to start the flogo-web process. Because of which the [EngineProcessDirector](https://github.com/project-flogo/flogo-web/blob/cc17197dbbd0b5c94257eb04d1bb414e979a16f5/apps/server/src/modules/engine/process/engine-process-director.ts#L26) was not maintaining the actual flogo-web process.
As the flogo-web process is not killed properly, the second time we are trying to start the process for simulation / flow testing, we see an error saying port is already in use. 
The changes should only effect the windows local environment.
=> [1277] Windows environment now maintain single instance of flogo-web process

VENDORS.md, package.json, yarn.lock
fix: Downgraded perspective-webpack-plugin to 0.3.8 to fix windows client serve command
Fixes #1283 
I am facing an error while serving client in windows environment. Downgrading the perspective webpack plugin fixed the problem.
We are not able to start the client in windows local environment.
Tested the stream simulation in regression in local environment and docker environment and made sure the behavior is same in both.
=> [1283] Fix angular serve in windows environment

libs/lib-client/diagram/src/index.ts, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.html, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.ts, libs/lib-client/diagram/src/lib/drag-tiles/drag-tile.service.ts, libs/lib-client/diagram/src/lib/drag-tiles/index.ts, libs/lib-client/diagram/src/lib/index.ts, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
I have removed dependency of flag [`CdkDragDrop.isPointerOverContainer`](https://material.angular.io/cdk/drag-drop/api#CdkDragDrop) to know if the drop is inside or outside a droplist. The library set's a wrong value to the flag when trying to place the tile as the last element of the row. 
The changes are in `@flogo-web/lib-client/diagram` and `@flogo-web/plugins/stream-client`.
Manally tested the flows and stream designer page with following scenarios:
=> [707] - Fix edge case where the dropping a tile as last element does not save

libs/plugins/flow-client/src/lib/core/models/flow/remove-node.ts
When all the tasks all deleted form the diagram, rootId in the graph has to be reset to null in the state
Tested manually using Redux DevTools browser extension
=> fix(plugins-flow-client): reset rootId when all nodes are deleted

libs/lib-client/diagram/src/lib/diagram.module.ts, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.html, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.less, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.ts, libs/lib-client/diagram/src/lib/diagram/diagram.component.html, libs/lib-client/diagram/src/lib/diagram/diagram.component.ts, libs/lib-client/diagram/src/lib/drag-tiles/drag-tile.service.ts, libs/lib-client/diagram/src/lib/tiles/tile-placeholder.component.ts, libs/lib-client/diagram/src/lib/tiles/tile-preview.component.html, libs/lib-client/diagram/src/lib/tiles/tile-preview.component.ts, libs/lib-client/diagram/src/lib/tiles/tiles-svg.component.html, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html
Implement visual designs for tile drag and drop. Changes include
part of #707 
=> [707] drag and drop visuals

apps/client/src/assets/main.less, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.html, libs/lib-client/diagram/src/lib/diagram/diagram-row.component.less, libs/lib-client/diagram/src/lib/diagram/diagram.component.ts, libs/lib-client/diagram/src/lib/drag-tiles/drag-tile.service.ts, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
I initially wanted to implemented this overriding cursor style by targeting the drag tile. But due to some technical limitation(https://github.com/angular/components/issues/15090) in CDK had to toggle the style for body.
=> feat(lib-client): drag drop visuals

libs/plugins/stream-client/src/lib/core/state/cases/stage-item-created.ts, libs/plugins/stream-client/src/lib/stage-add/add-stage.directive.ts, libs/plugins/stream-client/src/lib/stage-configurator/models/commit-stage-configuration.ts, libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.html, libs/plugins/stream-client/src/lib/stream-designer/stream-designer.component.ts, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.html, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.less, libs/plugins/stream-client/src/lib/stream-diagram/stream-diagram.component.ts
Ability to add a stage in between for streams
Part of #1299 
=> feat(plugins-stream-client): add stage in between

libs/plugins/flow-client/src/lib/debug-panel/debug-panel.component.less, libs/plugins/flow-client/src/lib/flow.component.html, libs/plugins/flow-client/src/lib/flow.component.less
This solves the issue #1321 "In flow when I select an activity that has both input and outputs and I open the debugger panel the panel content doesn't extend all the way to the right edge of the screen and there's a gap to the left of the scrollbar."
Manually
=> Flows: debugger panel scrollbar misalignment 

apps/server/src/api/ws/engine-log-streamer.ts
Fixed the issue where Anand said: "The logs when pop out to a new window does not show all the log messages. When I test run a flow, I can see the latest information again."
The messages are now latest when the logs are popped out to a new window. 
Manually
=> Fixed: Latest log messages are missing when I pop out to a new tab #1291

apps/client/src/flogo/app/export-flows/export-flows.component.html, apps/client/src/flogo/app/export-flows/export-flows.component.ts, apps/client/src/flogo/app/missing-trigger-confirmation/missing-trigger-confirmation.component.html, apps/client/src/flogo/app/shim-trigger/shim-trigger.component.html, apps/client/src/flogo/app/shim-trigger/shim-trigger.component.ts, apps/client/src/flogo/core/core.module.ts, libs/lib-client/common/src/lib/client-shared.module.ts, libs/lib-client/common/src/lib/directives/action-on-escape.ts, libs/lib-client/common/src/lib/directives/index.ts, libs/lib-client/confirmation/src/confirmation-modal/confirmation-modal.component.html, libs/lib-client/confirmation/src/confirmation-modal/confirmation-modal.component.ts, libs/lib-client/contrib-installer/src/lib/contrib-installer.component.html, libs/lib-client/modal/src/components/modal/modal.component.html, libs/lib-client/modal/src/components/modal/modal.component.ts, libs/plugins/flow-client/src/lib/branch-configurator/branch-configurator.component.html, libs/plugins/flow-client/src/lib/params-schema/params-schema.component.html, libs/plugins/flow-client/src/lib/sub-flow/sub-flow.component.html, libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.html, libs/plugins/flow-client/src/lib/task-configurator/task-configurator.component.ts, libs/plugins/flow-client/src/lib/triggers/configurator/configurator.component.html, libs/plugins/flow-client/src/lib/triggers/configurator/configurator.component.ts, libs/plugins/flow-client/src/lib/triggers/configurator/confirmation/confirmation.component.html, libs/plugins/flow-client/src/lib/triggers/configurator/confirmation/confirmation.component.ts, libs/plugins/stream-client/src/lib/params-schema/params-schema.component.html, libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.html, libs/plugins/stream-client/src/lib/stage-configurator/stage-configurator.component.ts, libs/plugins/stream-client/src/lib/triggers/configurator/configurator.component.html, libs/plugins/stream-client/src/lib/triggers/configurator/configurator.component.ts, libs/plugins/stream-client/src/lib/triggers/configurator/confirmation/confirmation.component.html, libs/plugins/stream-client/src/lib/triggers/configurator/confirmation/confirmation.component.ts
Close below mentioned modals/overlays on escape key press
- Task/stage configurator
- Trigger configurator
- Branch configurator
- Add trigger modal
-  Contribution install modal
-  Resource input/output configuration modal
-  Delete(resource/task/trigger/branch) confirmation modal
-  Help menu in the nav when clicked outside the menu window
Part of #1333 
=> [1333]close modals/overlays on escape

libs/plugins/stream-client/src/lib/core/effects/stream-save.effects.ts
Auto stop stream simulation when stages position changes
Tested manually.
Steps to test:
1) Create an app, add a stream action
2) Add stages(min 2) to the diagram, upload stream input file
3) Click run stream
4) Change the position of the stages by drag and drop to other position
5) Stream simulation should stop
=> fix: auto stop simulation

libs/lib-client/contrib-installer/src/lib/url-installer/url-installer.component.html
Validate input field of contrib install modal. Disable install button if the input is invalid.
Fixes #823
=> fix: disable install button when url input is empty

libs/parser/src/ast/ast-creator.ts
Mapper input is not validating the JSON value correct, it's treating the empty array([]) value as invalid. As soon as I type empty array as value to any key, input field becomes invalid and the save button grays out.
Manually
=> fix: validate json value correct in mapper
